### ISSUE TITLE
Travis CI is ending their free OSS builds

### ISSUE THREAD

**Issue by jcrist** [dask/community#107]
Travis CI is used by several repos in the org. Today they announced they are shutting down their free OSS builds (https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). Existing users get 10,000 free credits (1000 mins of linux build time), which is not nearly enough to support our CI needs. Per the blog post users can ask for more free credits, which they'll evaluate on a case-by-case basis.

Should we start migrating projects to a different CI system?

**Comment by martindurant** [comment]
I think *all* of the repos I manage are Travis, due to inertia :(
Would be very glad to be shown the smoothest way to move to githubActions.

**Comment by jacobtomlinson** [comment]
I'm happy to drive an effort to switch to Actions. I can make a start on this now.

Proposed steps:
- Add a list of all affected repos in this issue
- Write some clear instructions on how to migrate
- Open an issue on each repo
- Raise a PR on each repo to migrate the config
- Check off the list here

**Comment by jacobtomlinson** [comment]
## Migration steps

Here are some general steps to migrate from Travis CI to GitHub Actions. I'll update this as I work through some migrations to add more detail.

### Convert config

Create new CI config `.github/workflows/ci.yml` and open `.travis.yml` for reference.

Travis generally has some environment config such as OS, langauge, services, etc along with a build matrix. Then it has a few sections for running bash commands `pre_install`, `install`, `script`, etc.

In GitHub Actions we specify a trigger (e.g on pull request) and a list of jobs to be run. Each job has options such as OS selection and the option to specify a matrix. Then it has a series of steps. Each step can be a bash command or a prebaked "Action". To keep the migration simple it makes sense to use a couple of official Actions to configure the environment and then copy the existing bash commands from `.travis.yml`.

#### Example

Here's a simplified example of converting from one to the other.

```yaml
# .travis.yml

language: python

matrix:
  include:
    - python: 3.7
    - python: 3.8

install:
  - python -m pip install --upgrade pip
  - pip install flake8 pytest
  - pip install -r requirements.txt

script:
  - flake8
  - pytest
```

```yaml
# .github/workflows/ci.yml

name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8
    - name: Test with pytest
      run: |
        pytest
```

### Test workflow

Raise a PR and test the new workflow.

### Ensure Travis is disabled

Your PR to migrate should delete the `.travis.yml` file. This may be enough to disable Travis CI as there is a config option to only run Travis if the file exists which defaults to true. However you may still need to check this in the Travis settings.

### Update badges

We also need to update the README badges to point to the new workflow.

Badge URL: `https://github.com/<ORG>/<REPO>/workflows/<WORKFLOW NAME>/badge.svg`
Badge Link: `https://github.com/<ORG>/<REPO>/actions`

For example `dask-jobqueue` already uses GitHub Actions and has the following badge

**Markdown**

```markdown
[![Build Status](https://github.com/dask/dask-jobqueue/workflows/CI/badge.svg)](https://github.com/dask/dask-jobqueue/actions)
```

**RST**

```rst
.. |Build Status| image:: https://github.com/dask/dask-jobqueue/workflows/CI/badge.svg
   :target: https://github.com/dask/dask-jobqueue/actions
```

**Preview**

[![GitHub Actions Badge](https://github.com/dask/dask-jobqueue/workflows/CI/badge.svg)](https://github.com/dask/dask-jobqueue/actions)
